-- BATCH DAY
CREATE TABLE RDW_CFG.RDW_C_BATCH_DATE (
    BATCH_DATE DATE PRIMARY KEY,
    BATCH_ID BIGINT
);

-- EXTRACTION LOG
CREATE TABLE RDW_CFG.RDW_EXT_C_BATCH_LOG (
    BATCH_ID           BIGINT,
    JOB_ID             BIGINT,
    JOB_NAME           VARCHAR(255) NOT NULL,
    BUSINESS_DATE      DATE,
    STATUS             VARCHAR(50) NOT NULL,
    ROWS_PROCESSED     BIGINT,
    SOURCE_SYSTEM      VARCHAR(255),
    TARGET_TABLE       VARCHAR(255),
    START_TIME         TIMESTAMP NOT NULL,
    END_TIME           TIMESTAMP,
    CONSTRAINT UNIQ_BATCH_JOB_BUSINESS UNIQUE (BATCH_ID, JOB_ID, BUSINESS_DATE)
);

-- EXTRACTION SCRIPTS
CREATE TABLE RDW_CFG.RDW_EXT_C_BATCH_SCRIPTS (
    SCRIPT_ID           BIGINT PRIMARY KEY AUTOINCREMENT,
    SCRIPT_NAME         VARCHAR(100) NOT NULL,
    SCRIPT_DESCRIPTION  VARCHAR(255),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    LAST_RUN_DATE       DATE,
    NEXT_RUN_DATE       DATE,
    SCHEDULE_FREQUENCY  VARCHAR(20) DEFAULT 'DAILY'
);

-- LOADING LOG
CREATE TABLE RDW_CFG.RDW_LOAD_C_BATCH_LOG (
    BATCH_ID           BIGINT,
    JOB_ID             BIGINT,
    JOB_NAME           VARCHAR(255) NOT NULL,
    BUSINESS_DATE      DATE,
    STATUS             VARCHAR(50) NOT NULL,
    ROWS_PROCESSED     BIGINT,
    SOURCE_SYSTEM      VARCHAR(255),
    TARGET_TABLE       VARCHAR(255),
    START_TIME         TIMESTAMP NOT NULL,
    END_TIME           TIMESTAMP,
    CONSTRAINT UNIQ_BATCH_JOB_BUSINESS_LOADING UNIQUE (BATCH_ID, JOB_ID, BUSINESS_DATE)
);

-- LOADING SCRIPTS
CREATE TABLE RDW_CFG.RDW_LOAD_C_BATCH_SCRIPTS (
    SCRIPT_ID           BIGINT PRIMARY KEY AUTOINCREMENT,
    SCRIPT_NAME         VARCHAR(100) NOT NULL,
    SCRIPT_DESCRIPTION  VARCHAR(255),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    LAST_RUN_DATE       DATE,
    NEXT_RUN_DATE       DATE,
    SCHEDULE_FREQUENCY  VARCHAR(20) DEFAULT 'DAILY'
);
