-- BATCH DAY
RDW_CFG.RDW_C_BATCH_DATE

---EXTRACTION LOG 
CREATE TABLE RDW_CFG.RDW_EXT_C_BATCH_LOG (
    BATCH_ID           BIGINT IDENTITY(1,1),  -- UNIQUE IDENTIFIER FOR EACH BATCH/JOB RUN
    JOB_NAME           VARCHAR(255) NOT NULL, -- NAME OF THE ETL JOB
    START_TIME         TIMESTAMP NOT NULL,    -- START TIME OF THE ETL JOB
    END_TIME           TIMESTAMP,             -- END TIME OF THE ETL JOB
    STATUS             VARCHAR(50) NOT NULL,  -- STATUS OF THE JOB (E.G., 'SUCCESS', 'FAILED')
    ERROR_MESSAGE      VARCHAR(1000),         -- ANY ERROR MESSAGE ENCOUNTERED DURING THE RUN
    ROWS_PROCESSED     BIGINT,                -- NUMBER OF ROWS PROCESSED DURING THE JOB
    SOURCE_SYSTEM      VARCHAR(255),          -- NAME OF THE SOURCE SYSTEM FROM WHICH DATA IS BEING EXTRACTED
    TARGET_TABLE       VARCHAR(255),          -- NAME OF THE TARGET TABLE WHERE DATA IS BEING LOADED
    CREATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- LOG CREATION TIMESTAMP
    UPDATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- LOG UPDATE TIMESTAMP
);
